sudo: required
language: ruby
rvm:
- 2.1
before_install:
- openssl aes-256-cbc -K $encrypted_9987d5d337d3_key -iv $encrypted_9987d5d337d3_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 45.77.120.114\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- bundle install
- bundle exec jekyll build
after_success:
- rsync -rv --delete -e 'ssh -o stricthostkeychecking=no -p 22' public/_site root@nathanzhang.me:/usr/share/nginx/html
